#!/usr/bin/bash

##  uGameBoy, a gameboy emulator.
##  Copyright (C) 2019  Uğurcan Akkök
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License
##  along with this program.  If not, see <https://www.gnu.org/licenses/>.
##
##  to contact about this program, mail akkokugurcan@gmail.com

oldpwd=`pwd`
cd src
rom=../roms/tetris
log=../log.txt
make
#../bin/ugameboy $rom
../bin/ugameboy -x ../hexrom -l9 $rom
echo "====== TAIL LOG.TXT ====="
tail $log
echo "====== END OF TAIL LOG.TXT ====="

if [[ $( grep "CRITIC" $log ) ]];then
    echo "====== CRITIC MESSAGES ====="
    grep "CRITIC" $log
    echo "====== END OF CRITIC MESSAGES ====="
fi
cd $oldpwd
